server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kronos
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  application:
    name: dimiourgia

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
    api-docs:
        path: /dimiourgia/v3/api-docs
    swagger-ui:
        path: /dimiourgia/swagger-ui.html
